apiVersion: v2
name: vaultsecrets
version: 1.0.0
description: Generator of the secrets from remote Vault server
type: application
dependencies:
  - name: k8s-common
    version: 1.0.0
    repository: https://cere-io.github.io/kubernetes-helm-templates
home: https://cere-io.github.io/kubernetes-helm-templates
sources:
  - https://github.com/cere-io/kubernetes-helm-templates/tree/master/stable/vaultsecrets
maintainers:
  - name: Oleg Yankovich
    url: https://github.com/krolol
