{{ if .Values.env.vaultSecret }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" . }}-vault
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
spec:
  backendType: vault
  vaultRole: {{ .Release.Namespace }}
  kvVersion: 2
  data:
  {{- $allVaultSecrets := default (dict) .Values.env.vaultSecret -}}
  {{- range $key, $value := $allVaultSecrets }}
    - name: {{ $key }}
      key: {{ if $value.fullPath -}}
        {{- $value.fullPath -}}
        {{- else -}}
        secret-{{ $.Values.global.org }}/data/
        {{- $.Values.global.environmentType -}}
        /k8s/{{ $.Release.Namespace}}/{{ $value.path }}
      {{- end }}
      property: {{ default $key $value.secret }}
  {{ end -}}
{{ end -}}

{{- range .Values.sidecarContainers }}
{{- $values := dict "Values" . "Release" $.Release "Template" $.Template -}}
{{ if $values.Values.env.vaultSecret }}
{{ $name := default $.Release.Name $values.Values.global.serviceName }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" $values }}-vault
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  backendType: vault
  vaultRole: {{ $.Release.Namespace }}
  kvVersion: 2
  data:
  {{- $allVaultSecrets := default (dict) $values.Values.env.vaultSecret -}}
  {{- range $key, $value := $allVaultSecrets }}
    - name: {{ $key }}
      key: {{ if $value.fullPath -}}
        {{- $value.fullPath -}}
        {{- else -}}
        secret-{{ $.Values.global.org }}/data/
        {{- $.Values.global.environmentType -}}
        /k8s/{{ $.Release.Namespace}}/{{ $value.path }}
      {{- end }}
      property: {{ default $key $value.secret }}
  {{ end -}}
{{ end -}}
{{ end -}}

{{- if .Values.vaultVolumesSupport -}}
{{- $allVolumes := default (dict) .Values.volumes -}}
{{- range $key, $value := $allVolumes }}
{{- if $value.vaultPath -}}
{{- $vaultPath := $value.vaultPath }}
{{- $items := default (list) $value.items }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-common.names.fullname" $ }}-vault-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" $ | nindent 4 }}
spec:
  backendType: vault
  vaultRole: {{ $.Release.Namespace }}
  kvVersion: 2
  data:
  {{- range $items }}
    - name: {{ . }}
      key: secret-{{ $.Values.global.org }}/data/
        {{- $.Values.global.environmentType -}}
        /k8s/{{ $.Release.Namespace}}/{{ $vaultPath }}
      property: {{ . }}
  {{ end -}}
  {{ end -}}
  {{ end -}}
{{- end -}}
