{{- $allKubeSecrets := default (dict) .Values.kubeSecrets -}}
{{- $namespace := .Release.Namespace }}
{{- range $key, $value := $allKubeSecrets }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $key }}-vault
  namespace: {{ $namespace }}
spec:
  backendType: vault
  vaultRole: {{ $namespace }}
  kvVersion: 2
  data:
    {{- $vaultSecrets := default (dict) $value -}}
    {{- range $vaultValue := $vaultSecrets }}
    - name: {{ $vaultValue.name }}
      key: secret-{{ $.Values.global.org }}/data/
      {{- $.Values.global.environmentType -}}
      /k8s/{{ $namespace }}/{{ $vaultValue.path }}
      property: {{ default $vaultValue.name $vaultValue.secret }}
  {{ end -}}
  {{ end -}}
