name: test charts

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: lint
        run: |
          for x in ./stable/*; do
            pushd $x
            helm dependency update .
            helm lint . \
              --set global.org=core \
              --set global.serviceName=test \
              --with-subcharts \
              --strict
            popd
          done
      - name: validate
        run: |
          for x in ./stable/*; do
            if [[ "$x" != "./stable/k8s-common" ]]; then
              pushd $x
              helm template . \
                --debug \
                --generate-name \
                --namespace test \
                --dependency-update \
                --set global.pillar=core \
                --set global.serviceName=test \
                --values values.yaml
            popd
            fi
          done

